"""baseline schema

Revision ID: 469607f40ced
Revises: 
Create Date: 2026-09-19 04:02:39.853396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '469607f40ced'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('metadata_json', sa.String(length=4000), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=False),
    sa.Column('theme', sa.String(length=500), nullable=False),
    sa.Column('eligibility', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('application_open_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('application_close_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('judging_open_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('judging_close_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schools',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('school_name', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=False),
    sa.Column('province', sa.String(length=120), nullable=False),
    sa.Column('district', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('contact_phone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('applications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('competition_id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('project_title', sa.String(length=255), nullable=False),
    sa.Column('problem_description', sa.String(length=4000), nullable=False),
    sa.Column('solution_description', sa.String(length=4000), nullable=False),
    sa.Column('innovation_description', sa.String(length=4000), nullable=False),
    sa.Column('impact_description', sa.String(length=4000), nullable=False),
    sa.Column('implementation_plan', sa.String(length=4000), nullable=False),
    sa.Column('technology_used', sa.String(length=1000), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('teacher_coordinator', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('review_notes', sa.String(length=2000), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'school_id', name='uq_application_competition_school')
    )
    op.create_table('competition_participants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('competition_id', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'school_id', name='uq_competition_school')
    )
    op.create_table('judge_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('competition_id', sa.String(length=36), nullable=False),
    sa.Column('judge_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['judge_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'judge_id', name='uq_competition_judge')
    )
    op.create_table('rubrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('competition_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('competition_id', sa.String(length=36), nullable=False),
    sa.Column('judge_id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('weighted_total', sa.Float(), nullable=True),
    sa.Column('strengths', sa.String(length=2000), nullable=False),
    sa.Column('improvements', sa.String(length=2000), nullable=False),
    sa.Column('comments', sa.String(length=2000), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_saved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], ),
    sa.ForeignKeyConstraint(['judge_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('competition_id', 'judge_id', 'application_id', name='uq_evaluation_judge_application')
    )
    op.create_table('resources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('resource_type', sa.String(length=20), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('secure_filename', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('storage_location', sa.String(length=1000), nullable=False),
    sa.Column('upload_status', sa.String(length=30), nullable=False),
    sa.Column('ai_analysis_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rubric_criteria',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rubric_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('minimum_score', sa.Integer(), nullable=False),
    sa.Column('maximum_score', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rubric_id'], ['rubrics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('application_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_content_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('analysis_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('detected_sections', sa.String(length=4000), nullable=False),
    sa.Column('analysis_summary', sa.String(length=2000), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_notes', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evaluation_id', sa.String(length=36), nullable=False),
    sa.Column('criterion_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('weighted_contribution', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['rubric_criteria.id'], ),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_id', 'criterion_id', name='uq_evaluation_criterion')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation_scores')
    op.drop_table('ai_content_analyses')
    op.drop_table('team_members')
    op.drop_table('rubric_criteria')
    op.drop_table('resources')
    op.drop_table('evaluations')
    op.drop_table('rubrics')
    op.drop_table('judge_assignments')
    op.drop_table('competition_participants')
    op.drop_table('applications')
    op.drop_table('schools')
    op.drop_table('competitions')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
